choco install powertoys
choco install yed
choco install visualstudio2019community
choco install visualstudio2019buildtools
choco install postman
choco install insomnia-rest-api-client
choco install gimp
choco install curl
choco install vcredist140
choco install vscode
choco install vscode-drawio
choco install azurefunctions-vscode
choco install loki
choco install cmder
choco install gprolog-msvc
choco install tcpview
choco install notepadplusplus.install
choco install powershell
choco install poshgit
choco install windbg
choco install nugetpackagemanager
choco install dngrep
choco install adobereader
choco install 7zip.install
choco install sql-server-management-studio